"""tenant isolation

Revision ID: db17ab7db94a
Revises: a1b2c3d4e5fd
Create Date: 2026-10-01 23:53:04.055320

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import app.db.compiles_types

# revision identifiers, used by Alembic.
revision = 'db17ab7db94a'
down_revision = 'a1b2c3d4e5fd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', app.db.compiles_types.SqliteCompatibleBigInteger(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_groups_tenant_id_tenants'), 'tenants', ['tenant_id'], ['id'])

    with op.batch_alter_table('hosts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', app.db.compiles_types.SqliteCompatibleBigInteger(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_hosts_tenant_id_tenants'), 'tenants', ['tenant_id'], ['id'])

    with op.batch_alter_table('oc_panels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', app.db.compiles_types.SqliteCompatibleBigInteger(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_oc_panels_tenant_id_tenants'), 'tenants', ['tenant_id'], ['id'])

    # Backfill tenant_id from purchaser_identity
    op.execute(
        "UPDATE oc_panels "
        "SET tenant_id = admins.tenant_id "
        "FROM admins "
        "WHERE oc_panels.purchaser_identity = admins.username"
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oc_panels', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_oc_panels_tenant_id_tenants'), type_='foreignkey')
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('hosts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_hosts_tenant_id_tenants'), type_='foreignkey')
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_groups_tenant_id_tenants'), type_='foreignkey')
        batch_op.drop_column('tenant_id')

    # ### end Alembic commands ###
